### ISSUE TITLE
Add to WP.org Repo

### ISSUE THREAD

**Issue by themightymo** [gndev/toolbar-edit-links-for-gravity-forms#1]
I use this plugin on all my sites - a huge timesaver.  Ever thought of putting it in the wp.org repo  (it'd certainly get rid of one barrier to installing and better-serve the greater WP community)?  

If not, would you mind if I made a clone for that repo?

Here's my profile: https://profiles.wordpress.org/themightymo#content-plugins

**Comment by vanokhin** [comment]
The plugin is already there: [Admin Bar Edit Links for Gravity Forms](https://wordpress.org/plugins/admin-bar-edit-links-for-gravity-forms/)

**Comment by themightymo** [comment]
Oh beautiful!  Didn't realize that - thank you!
